/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.rpenates.tiappsflyer;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;

import com.appsflyer.AppsFlyerLib;

import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;


@Kroll.module(name="TiAppsFlyer", id="com.rpenates.tiappsflyer")
public class TiAppsFlyerModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "[TiAppsFlyerModule]";
	private static final boolean DBG = TiConfig.LOGD;
	private static TiApplication tiapp;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public TiAppsFlyerModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is created
		Log.d(LCAT, "app content: " + app.toString());
		tiapp = app;
	}

	// Methods

	@Kroll.method
	public void initTracker(String appsflyerKey) {
		Log.d(LCAT, "Init with AppsFlyer key: " + appsflyerKey.substring(0, 6) + "...");
		AppsFlyerLib.getInstance().startTracking(tiapp, appsflyerKey);
	}

}

